config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  mount Sidekiq::Web => '/sidekiq'
  get 'health-check', to: 'health_check#check', as: :health_check

  get 'dashboard', to: 'dashboard#show', as: :dashboard

  resources :profiles, except: :destroy

  resources :identity_statements, path: 'identity-statements' do
    get 'new-reset', to: 'identity_statements#new_reset', as: :new_reset, on: :collection
  end

  get 'me', to: 'profiles#me', as: :user_profile

  scope :settings do
    get '/', to: 'settings#show', as: :settings
    get '/details', to: 'settings#details', as: :account_details
    get '/details/edit', to: 'settings#edit_details', as: :edit_account_details
    put '/details', to: 'settings#update_details', as: :update_account_details
    get '/password', to: 'settings#password', as: :change_password
    put '/password', to: 'settings#update_password', as: :update_password
    get '/password/edit', to: 'settings#edit_password', as: :change_password_form
    get '/account/delete', to: 'settings#delete_account', as: :delete_account
    delete '/account/delete', to: 'settings#destroy_account', as: :destroy_account
  end

  root to: 'home#index'
end

app/models/profile.rb
# frozen_string_literal: true

##
# Models a user profile.
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true, length: { maximum: 40 }
  validates :last_name, presence: true, length: { maximum: 40 }

  def name?
    first_name && last_name
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

##
# Controller for profile endpoints.
class ProfilesController < ApplicationController
  include Onboardable

  skip_before_action :onboard_user, only: %i[new create]
  before_action :set_user
  before_action :set_profile_for_current_user, only: %i[me edit update]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
  end

  # GET /me or me.json
  def me
    render :show
  end

  # GET /profiles/new
  def new
    redirect_to profile_path(current_user.profile) and return if current_user.profile.present?

    @profile = Profile.new(user: current_user)
  end

  # GET /profiles/1/edit
  def edit; end

  # POST /profiles or /profiles.json
  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def create
    redirect_to user_profile_path and return if current_user.profile.present?

    @profile = Profile.new(profile_params.merge(user: current_user))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to dashboard_path, notice: 'Welcome to Kutima! You\'re ready to start optimizing.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to user_profile_path, notice: 'Profile was successfully updated.' }
        format.turbo_stream { render :update_success }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream { render :update_failure }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  private

  def set_user
    @user = current_user
  end

  def set_profile_for_current_user
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(%i[id first_name last_name])
  end
end

app/views/profiles/_form.html.erb
<%= form_with model: profile, id: dom_id(profile), class: 'w-100 m-auto' do |f| %>
  <%= render(FormGroupComponent.new(form: f, field: :first_name, errors: profile.errors)) do |c| %>
    <% c.label('First Name') %>
    <% c.text(html_options: {}) %>
  <% end %>
  <%= render(FormGroupComponent.new(form: f, field: :last_name, errors: profile.errors)) do |c| %>
    <% c.label('Last Name') %>
    <% c.text(html_options: {}) %>
  <% end %>
  <%= tag.div class: 'text-center mt-6' do %>
    <%= render(ButtonTagComponent.new(options: { data: { turbo: false } })) do %>
        Save
    <% end %>
  <% end %>
<% end %>

app/views/profiles/_profile.html.erb
<%= turbo_frame_tag dom_id(profile) do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.header do %>
      <div class="ml-1">
        <%= link_to edit_profile_path(current_user.profile), class: 'no-underline focus:outline-none transition-colors text-yellow-400 hover:text-yellow-500' do %>
          <i class="fas fa-pencil-alt fa-lg" title="Edit"></i>
        <% end %>
      </div>
    <% end if profile.id == current_user.profile.id %>
    <% c.body do %>
      <%= tag.h2 profile.user.username, class: UtilityClasses.for(:heading, variant: :xl) %>
      <%= tag.p "#{profile.first_name} #{profile.last_name}", class: 'text-center dark:text-white' %>
      <%= tag.p "Member since #{profile.user.created_at.strftime("%m/%d/%Y")}", class: 'text-center dark:text-white' %>
    <% end %>
  <% end %>
<% end %>

app/views/profiles/edit.html.erb
<%= turbo_frame_tag dom_id(@profile) do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.header do %>
      <%= link_to settings_path, class: 'text-gray-900 dark:text-white hover:text-gray-500 ml-2', data: { 'turbo-frame': dom_id(@profile) } do %>
        <i class="fas fa-arrow-left fa-lg" title="Back"></i>
      <% end %>
    <% end %>
    <% c.body do %>
      <%= render partial: 'profiles/form', locals: { profile: @profile, submit_text: 'Update' } %>
    <% end %>
  <% end %>
<% end %>

app/views/profiles/index.html.erb
<%= turbo_stream_from 'profiles' %>
<%= turbo_frame_tag :profiles do %>
  <%= render @profiles %>
<% end %>

app/views/profiles/new.html.erb
<%= render(CardComponent.new) do |c| %>
  <% c.body do %>
    <h2 class="dark:text-white text-center text-4xl">Almost There</h2>
    <%= render partial: 'profiles/form', locals: { profile: @profile, submit_text: 'Finish' } %>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<%= turbo_frame_tag dom_id(@profile) do %>
  <%= render @profile %>
<% end %>

app/views/profiles/update_failure.turbo_stream.erb
<%= turbo_stream.replace dom_id(@profile) do %>
  <%= render template: 'profiles/edit' %>
<% end %>

app/views/profiles/update_success.turbo_stream.erb
<%= turbo_stream.replace dom_id(@profile) do %>
  <%= render @profile %>
<% end %>