config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  mount Sidekiq::Web => '/sidekiq'
  get 'health-check', to: 'health_check#check', as: :health_check

  get 'dashboard', to: 'dashboard#show', as: :dashboard

  resources :profiles, except: :destroy

  resources :identity_statements, path: 'identity-statements' do
    get 'new-reset', to: 'identity_statements#new_reset', as: :new_reset, on: :collection
  end

  get 'me', to: 'profiles#me', as: :user_profile

  scope :settings do
    get '/', to: 'settings#show', as: :settings
    get '/details', to: 'settings#details', as: :account_details
    get '/details/edit', to: 'settings#edit_details', as: :edit_account_details
    put '/details', to: 'settings#update_details', as: :update_account_details
    get '/password', to: 'settings#password', as: :change_password
    put '/password', to: 'settings#update_password', as: :update_password
    get '/password/edit', to: 'settings#edit_password', as: :change_password_form
    get '/account/delete', to: 'settings#delete_account', as: :delete_account
    delete '/account/delete', to: 'settings#destroy_account', as: :destroy_account
  end

  root to: 'home#index'
end

app/models/identity_statement.rb
# frozen_string_literal: true

##
# Models an identity statement.
class IdentityStatement < ApplicationRecord
  belongs_to :user

  enum life_area: LifeArea::AREAS, _suffix: true

  validates :life_area, presence: true, inclusion: { in: LifeArea::AREAS.values }
  validates :identity, presence: true, length: { minimum: 3, maximum: 45 }
  validates :objective, presence: true, length: { minimum: 3, maximum: 255 }
end

app/controllers/identity_statements_controller.rb
# frozen_string_literal: true

##
# Controller for identity statement resources.
class IdentityStatementsController < ApplicationController
  before_action :set_identity_statement, only: %i[show edit update destroy]

  # GET /identity-statements
  def index
    @identity_statements = current_user.identity_statements
  end

  # GET /identity-statements/new
  def new
    @identity_statement = IdentityStatement.new
  end

  # GET /identity-statements/new-reset
  def new_reset; end

  # GET /identity-statements/:id
  def show; end

  # GET /identity-statements/:id/edit
  def edit; end

  # POST /identity-statements
  def create
    @identity_statement = IdentityStatement.new(identity_statement_params.merge(user: current_user))
    respond_to do |format|
      if @identity_statement.save
        format.html { redirect_to identity_statement_path(@identity_statement) }
        format.turbo_stream { render :create_success }
      else
        format.html { render :new }
        format.turbo_stream { render :create_failure }
      end
    end
  end

  # PATCH/PUT /identity-statements/:id
  def update
    respond_to do |format|
      if @identity_statement.update(identity_statement_params)
        format.html { redirect_to identity_statement_path(@identity_statement) }
        format.turbo_stream { render :update_success }
      else
        format.html { render :edit }
        format.turbo_stream { render :update_failure }
      end
    end
  end

  # DELETE /identity-statements/:id
  def destroy
    @identity_statement.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  private

  def set_identity_statement
    @identity_statement = IdentityStatement.find(params[:id])
  end

  def identity_statement_params
    params.require(:identity_statement).permit(%i[identity objective life_area user_id])
  end
end

app/views/identity_statements/_form.html.erb
<%= form_with model: identity_statement, id: dom_id(identity_statement), class: 'w-100 m-auto' do |f| %>
  <%= render(FormGroupComponent.new(form: f, field: :life_area, errors: identity_statement.errors)) do |c| %>
    <% c.label('Life Area') %>
    <% c.select(
         options_for_select(LifeArea::AREAS.transform_keys {|key| key.capitalize }, identity_statement.life_area),
         options: { include_blank: 'Select life area...' }
       ) %>
  <% end %>
  <%= render(FormGroupComponent.new(form: f, field: :identity, errors: identity_statement.errors)) do |c| %>
    <% c.label('I am a(n)...') %>
    <% c.text(html_options: { autocomplete: 'off', autocorrect: 'off', autocapitalize: 'off', spellcheck: false }) %>
  <% end %>
  <%= render(FormGroupComponent.new(form: f, field: :objective, errors: identity_statement.errors)) do |c| %>
    <% c.label('who...') %>
    <% c.text(html_options: { autocomplete: 'off', autocorrect: 'off', autocapitalize: 'off', spellcheck: false }) %>
  <% end %>
  <%= tag.div class: 'text-center mt-6' do %>
    <%= render(ButtonTagComponent.new) do %>
        <%= raw(submit_text) %>
    <% end %>
  <% end %>
<% end %>

app/views/identity_statements/_identity_statement.html.erb
<%= turbo_frame_tag dom_id(identity_statement) do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.header do %>
      <div class="ml-1">
        <%= link_to identity_statement_path(identity_statement.id), method: 'delete', class: 'no-underline focus:outline-none transition-colors text-red-500 hover:text-red-600 mr-1', data: { confirm: 'Are you sure?' } do %>
          <i class="fas fa-trash-alt fa-lg" title="Delete"></i>
        <% end %>
        <%= link_to edit_identity_statement_path(identity_statement.id), class: 'no-underline focus:outline-none transition-colors text-yellow-400 hover:text-yellow-500 ml-1', data: { 'turbo-frame': @turbo_frame_id } do %>
          <i class="fas fa-pencil-alt fa-lg" title="Edit"></i>
        <% end %>
      </div>
      <%= render(LifeAreaTagComponent.new(area: identity_statement.life_area)) %>
    <% end %>
    <%= c.body do |c| %>
      <%= tag.p t('pages.identity-statements.statement-template',
                  identity: (tag.span identity_statement.identity, class: 'border-solid border-b-4 border-purple-500 rounded-md'),
                  objective: (tag.span identity_statement.objective, class: 'border-solid border-b-4 border-blue-500 rounded-md')
                 ).html_safe,
                class: 'text-2xl text-center text-gray-900 dark:text-white' %>
    <% end %>
  <% end %>
<% end %>

app/views/identity_statements/create_failure.turbo_stream.erb
<%= turbo_stream.replace :new_identity_statement do %>
  <%= render template: 'identity_statements/new' %>
<% end %>

app/views/identity_statements/create_success.turbo_stream.erb
<%= turbo_stream.replace :new_identity_statement do %>
  <%= render template: 'identity_statements/new_reset' %>
<% end %>

<%= turbo_stream.prepend :identity_statements do %>
  <%= render @identity_statement %>
<% end %>

app/views/identity_statements/destroy.turbo_stream.erb
<%= turbo_stream.remove @identity_statement %>

app/views/identity_statements/edit.html.erb
<%= turbo_frame_tag dom_id(@identity_statement) do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.header do %>
      <%= link_to identity_statement_path(@identity_statement), class: 'text-gray-900 dark:text-white hover:text-gray-500 ml-2', data: { 'turbo-frame': dom_id(@identity_statement) } do %>
        <i class="fas fa-arrow-left fa-lg" title="Back"></i>
      <% end %>
    <% end %>
    <% c.body do %>
      <%= render partial: 'identity_statements/form',
        locals: {
          identity_statement: @identity_statement,
          submit_text: 'Save'
        } %>
    <% end %>
  <% end %>
<% end %>

app/views/identity_statements/index.html.erb
<%= turbo_frame_tag :identity_statements do %>
  <%= render @identity_statements %>
<% end %>

app/views/identity_statements/new.html.erb
<%= turbo_frame_tag :new_identity_statement do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.header do %>
      <%= link_to new_reset_identity_statements_path, class: 'text-gray-900 hover:text-gray-500 ml-2', data: { 'turbo-frame': :new_identity_statement } do %>
        <i class="fas fa-arrow-left fa-2x" title="Back"></i>
      <% end %>
    <% end %>
    <% c.body do %>
      <%= render partial: 'identity_statements/form',
        locals: {
          identity_statement: @identity_statement,
          submit_text: '<i class="fas fa-bullhorn"></i>&nbsp;Make a Statement'
        } %>
    <% end %>
  <% end %>
<% end %>

app/views/identity_statements/new_reset.html.erb
<%= turbo_frame_tag :new_identity_statement do %>
  <div class="flex flex-wrap justify-center mt-4 mb-6 mx-auto">
    <%= render(ButtonToComponent.new(link: new_identity_statement_path, method: :get, options: { variant: :outline_blue })) do %>
      <i class="fas fa-bullhorn"></i>&nbsp;Make a Statement
    <% end %>
  </div>
<% end %>

app/views/identity_statements/show.html.erb
<%= turbo_frame_tag :new_identity_statement do %>
  <%= render @identity_statement %>
<% end %>

app/views/identity_statements/update_failure.turbo_stream.erb
<%= turbo_stream.replace dom_id(@identity_statement) do %>
  <%= render template: 'identity_statements/edit' %>
<% end %>

app/views/identity_statements/update_success.turbo_stream.erb
<%= turbo_stream.replace dom_id(@identity_statement) do %>
  <%= render @identity_statement %>
<% end %>