config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  mount Sidekiq::Web => '/sidekiq'
  get 'health-check', to: 'health_check#check', as: :health_check

  get 'dashboard', to: 'dashboard#show', as: :dashboard

  resources :profiles, except: :destroy

  resources :identity_statements, path: 'identity-statements' do
    get 'new-reset', to: 'identity_statements#new_reset', as: :new_reset, on: :collection
  end

  get 'me', to: 'profiles#me', as: :user_profile

  scope :settings do
    get '/', to: 'settings#show', as: :settings
    get '/details', to: 'settings#details', as: :account_details
    get '/details/edit', to: 'settings#edit_details', as: :edit_account_details
    put '/details', to: 'settings#update_details', as: :update_account_details
    get '/password', to: 'settings#password', as: :change_password
    put '/password', to: 'settings#update_password', as: :update_password
    get '/password/edit', to: 'settings#edit_password', as: :change_password_form
    get '/account/delete', to: 'settings#delete_account', as: :delete_account
    delete '/account/delete', to: 'settings#destroy_account', as: :destroy_account
  end

  root to: 'home#index'
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

##
# Controller for account settings.
class SettingsController < ApplicationController
  include Onboardable

  before_action :set_user

  # GET /settings
  def show; end

  # GET /settings/details
  def details; end

  # GET /settings/details/edit
  def edit_details; end

  # PUT /settings/details
  def update_details
    respond_to do |format|
      if @user.update(update_details_params)
        bypass_sign_in(@user)
        format.html { redirect_to settings_path }
        format.turbo_stream { render :update_details_success }
      else
        format.html { render :edit_details }
        format.turbo_stream { render :update_details_failure }
      end
    end
  end

  # GET /settings/password
  def password; end

  # GET /settings/password/edit
  def edit_password; end

  # PUT /settings/password
  def update_password
    respond_to do |format|
      if @user.update_with_password(update_password_params)
        bypass_sign_in(@user)
        format.html { redirect_to settings_path }
        format.turbo_stream { render :update_password_success }
      else
        format.html { render :edit_password }
        format.turbo_stream { render :update_password_failure }
      end
    end
  end

  # GET /settings/account/delete
  def delete_account; end

  # DELETE /settings/account/delete
  def destroy_account
    respond_to do |format|
      if @user.valid_password?(destroy_account_params[:password])
        @user.destroy
        format.html { redirect_to root_path, notice: 'Account successfully deleted!' }
      else
        @user.errors.add(:password, 'is incorrect')
        format.html { render :delete_account }
      end
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_profile
    @profile = current_user.profile
  end

  def update_details_params
    params.require(:user).permit(:email, :username, profile_attributes: %i[id first_name last_name])
  end

  def update_password_params
    params.require(:user).permit(%i[password password_confirmation current_password])
  end

  def destroy_account_params
    params.require(:user).permit(:password)
  end
end

app/views/settings/delete_account.html.erb
<%= render(CardComponent.new) do |c| %>
  <% c.body do %>
    <%= link_to settings_path, class: 'text-gray-900 dark:text-white hover:text-gray-500 ml-2' do %>
      <i class="fas fa-arrow-left fa-lg" title="Back"></i>
    <% end %>
    <%= tag.h2 'Delete Account', class: UtilityClasses.for(:heading, variant: :xl) %>
    <%= form_for(@user, url: destroy_account_path, method: :delete) do |f| %>
      <p class="block mx-auto my-2 p-4 w-full text-center text-red-700 bg-red-200 border-2 border-red-700 rounded-md">
        Enter your password to confirm that you want to delete your account.
      </p>
      <%= render(FormGroupComponent.new(form: f, field: :password, errors: @user.errors)) do |c| %>
        <%= c.label 'Password' %>
        <%= c.text html_options: { type: 'password', autofocus: true, autocomplete: 'new-password' } %>
      <% end %>
      <%= tag.div class: 'text-center mt-6 mb-4' do %>
        <%= render(ButtonTagComponent.new(options: { variant: :solid_red, data: { turbo: 'false' }})) do %>
          Delete Account
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/settings/details.html.erb
<%= turbo_frame_tag :details do %>
  <div class="mr-1 mb-2 text-right">
    <%= link_to edit_account_details_path, class: 'no-underline focus:outline-none transition-colors text-yellow-400 hover:text-yellow-500' do %>
      <i class="fas fa-pencil-alt fa-lg" title="Edit"></i>
    <% end %>
  </div>
  <div class="mb-4 mt-2 ml-2 p-2">
    <p class="font-semibold mb-1">First Name</p>
    <p class="m-2 p-2"><%= @user.profile.first_name %></p>
  </div>
  <div class="mb-4 mt-2 ml-2 p-2">
    <p class="font-semibold mb-1">Last Name</p>
    <p class="m-2 p-2"><%= @user.profile.last_name %></p>
  </div>
  <div class="mb-4 mt-2 ml-2 p-2">
    <p class="font-semibold mb-1">Email</p>
    <p class="m-2 p-2"><%= @user.email %></p>
    <%= tag.p class: 'text-green-500' do %>
      <i class="fa fa-check"></i>&nbsp;Confirmed</p>
    <% end if @user.confirmed_at %>
  </div>
  <div class="mb-4 mt-2 ml-2 p-2">
    <p class="font-semibold mb-1">Username</p>
    <p class="m-2 p-2"><%= @user.username %></p>
  </div>
<% end %>

app/views/settings/edit_details.html.erb
<%= turbo_frame_tag :details do %>
  <%= link_to account_details_path, class: 'hover:text-gray-500 ml-2' do %>
    <i class="fas fa-arrow-left fa-lg" title="Back"></i>
  <% end %>
  <%= form_for(@user, url: update_account_details_path, method: :put) do |f| %>
    <%= f.fields_for :profile do |profile_form| %>
      <%= render(FormGroupComponent.new(form: profile_form, field: :first_name, errors: @user.profile.errors)) do |c| %>
        <% c.label('First Name') %>
        <% c.text(html_options: {}) %>
      <% end %>
      <%= render(FormGroupComponent.new(form: profile_form, field: :last_name, errors: @user.profile.errors)) do |c| %>
        <% c.label('Last Name') %>
        <% c.text(html_options: {}) %>
      <% end %>
    <% end %>
    <%= tag.div do %>
      <p class="block mx-auto my-2 p-4 w-full md:w-3/4 text-center text-yellow-500 dark:text-yellow-50 bg-yellow-50 dark:bg-yellow-500 border-2 border-yellow-500 rounded-md">
        Currently waiting confirmation for: <%= @user.unconfirmed_email %>
      </p>
    <% end if Devise.mappings[:user].confirmable? && @user.pending_reconfirmation? %>
    <%= render(FormGroupComponent.new(form: f, field: :email, errors: @user.errors)) do |c| %>
      <%= c.label 'Email' %>
      <%= c.text html_options: { type: 'email', autofocus: true, autocomplete: 'email' } %>
    <% end %>
    <%= render(FormGroupComponent.new(form: f, field: :username, errors: @user.errors)) do |c| %>
      <%= c.label 'Username' %>
      <%= c.text html_options: { autocomplete: 'off', autocorrect: 'off', autocapitalize: 'off', spellcheck: false } %>
    <% end %>
    <%= tag.div class: 'text-center mt-6 mb-4' do %>
      <%= render(ButtonTagComponent.new) do %>
          Save Changes
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/settings/edit_password.html.erb
<%= turbo_frame_tag :password do %>
  <div class="border-2 border-solid border-gray-200 dark:border-gray-600 rounded-md my-2 p-2">
    <%= link_to change_password_path, class: 'hover:text-gray-500 ml-2' do %>
      <i class="fas fa-arrow-left fa-lg" title="Back"></i>
    <% end %>
    <%= form_for(@user, url: update_password_path, method: :put) do |f| %>
      <%= render(FormGroupComponent.new(form: f, field: :current_password, errors: @user.errors)) do |c| %>
        <%= c.label 'Current Password' %>
        <%= c.text html_options: { type: 'password', autofocus: true, autocomplete: 'new-password' } %>
        <small>we need your current password to confirm your changes</small>
      <% end %>
      <%= render(FormGroupComponent.new(form: f, field: :password, errors: @user.errors)) do |c| %>
        <%= c.label 'New Password' %>
        <%= c.text html_options: { type: 'password', autofocus: true, autocomplete: 'new-password' } %>
        <small>(<%= @minimum_password_length %> characters minimum)</small>
      <% end %>
      <%= render(FormGroupComponent.new(form: f, field: :password_confirmation, errors: @user.errors)) do |c| %>
        <%= c.label 'Confirm Password' %>
        <%= c.text html_options: { type: 'password', autofocus: true, autocomplete: 'new-password' } %>
        <small>leave blank if you don't want to change it</small>
      <% end %>
      <%= tag.div class: 'text-center mt-6 mb-4' do %>
        <%= render(ButtonTagComponent.new) do %>
          Change Password
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/settings/password.html.erb
<%= turbo_frame_tag :password do %>
  <%= tag.div do %>
    <p class="block mx-auto my-2 p-4 w-full md:w-3/4 text-center text-green-700 bg-green-200 border-2 border-green-700 rounded-md">
      Password changed!
    </p>
  <% end if local_assigns[:success] %>
  <div class="flex flex-wrap justify-center my-4 mx-auto">
    <%= render(ButtonToComponent.new(link: change_password_form_path, method: :get, options: { variant: :outline_blue })) do %>
      Change Password
    <% end %>
  </div>
<% end %>

app/views/settings/show.html.erb
<%= turbo_frame_tag dom_id(@user) do %>
  <%= render(CardComponent.new) do |c| %>
    <% c.body do %>
      <%= tag.h2 'Account Settings', class: UtilityClasses.for(:heading, variant: :xl) %>
      <div class="border-2 border-solid border-gray-200 dark:border-gray-600 rounded-md my-2 p-2">
        <%= turbo_frame_tag :details do %>
          <%= render template: 'settings/details' %>
        <% end %>
      </div>
      <%= turbo_frame_tag :password do %>
        <%= render template: 'settings/password' %>
      <% end %>
      <div class="text-center">
        <%= link_to 'View My Profile', user_profile_path, class: 'text-lg text-blue-500 hover:text-blue-700 m-2 p-2 underline', data: { turbo: false } %>
      </div>
    <% end %>
  <% end %>
<% end %>
<%= render(CardComponent.new) do |c| %>
  <% c.body do %>
    <p class="text-center md:w-3/4 mx-auto">No longer satisfied with Kutima? Delete your account at anytime, and we won't hassle you.</p>
    <div class="flex flex-wrap justify-center my-4 mx-auto">
      <%= render(ButtonToComponent.new(link: delete_account_path, method: :get , options: { variant: :solid_red, data: { turbo: 'false' }})) do %>
        Delete Account
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/settings/update_details_failure.turbo_stream.erb
<%= turbo_stream.replace :details do %>
  <%= render template: 'settings/edit_details' %>
<% end %>

app/views/settings/update_details_success.turbo_stream.erb
<%= turbo_stream.replace :details do %>
  <%= render template: 'settings/details', locals: { success: true } %>
<% end %>

app/views/settings/update_password_failure.turbo_stream.erb
<%= turbo_stream.replace :password do %>
  <%= render template: 'settings/edit_password' %>
<% end %>

app/views/settings/update_password_success.turbo_stream.erb
<%= turbo_stream.replace :password do %>
  <%= render template: 'settings/password', locals: { success: true } %>
<% end %>